enum ActionTypes {
  JOIN_LQS = "JOIN_LQS",
  LEAVE_LQS = "LEAVE_LQS",
  KICK_PARTICIPANT = "KICK_PARTICIPANT",
  START_LQS = "START_LQS",
  END_LQS = "END_LQS",
  NEXT_QUESTION = "NEXT_QUESTION",
  DISTRIBUTE_QUESTION = "DISTRIBUTE_QUESTION",
  DISTRIBUTE_MEDIA = "DISTRIBUTE_MEDIA",
  DISTRIBUTE_OPTIONS = "DISTRIBUTE_OPTIONS",
  REVEAL_ANSWER = "REVEAL_ANSWER",
  CONCLUDE = "CONCLUDE",
  COUNTDOWN = "COUNTDOWN",

  TOGGLE_LOCK = "TOGGLE_LOCK",
  INTERRUPT = "INTERRUPT",
  GET_PARTICIPANTS = "GET_PARTICIPANTS",
  SUBMIT_ANSWER = "SUBMIT_ANSWER",
  UNSUBMIT_ANSWER = "UNSUBMIT_ANSWER",
  GET_LEADERBOARD = "GET_LEADERBOARD",
}

export default ActionTypes;
