enum ActionTypes {
  JOINED_LQS = "JOINED_LQS",
  LEFT_LQS = "LEFT_LQS",
  START_LQS = "START_LQS",
  NEXT_QUESTION = "NEXT_QUESTION",
  END_LQS = "END_LQS",
  DISTRIBUTE_QUESTION = "DISTRIBUTE_QUESTION",
  DISTRIBUTE_OPTIONS = "DISTRIBUTE_OPTIONS",
  REVEAL_ANSWER = "REVEAL_ANSWER",
  COUNTDOWN = "COUNTDOWN",
}

export default ActionTypes;
