enum Statuses {
  IDLE = "IDLE",
  STARTING = "STARTING",
  ENDING = "ENDING",
  QUESTIONING = "QUESTIONING",
  MEDIA = "MEDIA",
  ANSWERING = "ANSWERING",
  REVEALING_ANSWER = "REVEALING_ANSWER",
  LEADERBOARD = "LEADERBOARD",
  CONCLUDING = "CONCLUDING",
}

export default Statuses;
