# Use an official Node.js runtime as a base image
FROM --platform=linux/amd64 node:21.6.1

# Set the working directory inside the container
WORKDIR /app

# Copy the rest of the application code to the container
COPY . .

RUN corepack enable

# Expose the port the app runs on
EXPOSE 3000

# Start the development server
CMD ["pnpm","vite","serve","--host","0.0.0.0"]
